from sqlalchemy import Column, String, DateTime, Boolean, Integer, Float, ForeignKey, Enum, Text, Index, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from core.database import Base
import enum


class User(Base):
    __tablename__ = "users"

    user_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    full_name = Column(String, nullable=False)
    email = Column(String, unique=True, nullable=False)
    password_hash = Column(String, nullable=False)
    gemini_api_key = Column(String, nullable=True)  # Encrypted, not unique (each user has their own)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    schemas = relationship("APISchema", back_populates="user", cascade="all, delete-orphan")
    test_runs = relationship("TestRun", back_populates="user", cascade="all, delete-orphan")




# Enum for HTTP methods
class HTTPMethod(str, enum.Enum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    PATCH = "PATCH"
    HEAD = "HEAD"
    OPTIONS = "OPTIONS"

# Enum for test status
class TestStatus(str, enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    PASSED = "passed"
    FAILED = "failed"
    ERROR = "error"

# Enum for failure severity
class FailureSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class APISchema(Base):
    __tablename__ = "api_schemas"
    
    schema_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False)
    
    # Original user input
    original_filename = Column(String, nullable=False)
    base_url = Column(String, nullable=False)  # From user input
    
    # AI-processed data
    normalized_schema = Column(JSON, nullable=False)  # Agent 1 output
    schema_hash = Column(String(64), unique=True, index=True, nullable=False)  # For caching
    
    # Test cases generated by Agent 1
    test_cases = Column(JSON, nullable=False)  # List of test cases
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="schemas")
    test_runs = relationship("TestRun", back_populates="schema", cascade="all, delete-orphan")
    
    __table_args__ = (
        Index('idx_schema_hash', 'schema_hash'),
    )

class TestRun(Base):
    __tablename__ = "test_runs"
    
    run_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    schema_id = Column(Integer, ForeignKey("api_schemas.schema_id", ondelete="CASCADE"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False)
    
    # Execution metadata
    status = Column(Enum(TestStatus), default=TestStatus.PENDING, nullable=False)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    
    # Results summary
    total_tests = Column(Integer, default=0)
    passed_tests = Column(Integer, default=0)
    failed_tests = Column(Integer, default=0)
    error_tests = Column(Integer, default=0)
    
    # Stability score (MANDATORY per spec)
    stability_score = Column(Float, nullable=True)  # 0-100
    
    # Agent usage tracking (for cost control)
    agent1_called = Column(Boolean, default=False)
    agent2_called = Column(Boolean, default=False)
    
    # Relationships
    schema = relationship("APISchema", back_populates="test_runs")
    user = relationship("User", back_populates="test_runs")
    failures = relationship("TestFailure", back_populates="test_run", cascade="all, delete-orphan")
    
    __table_args__ = (
        Index('idx_user_run', 'user_id', 'started_at'),
    )

class TestFailure(Base):
    __tablename__ = "test_failures"
    
    failure_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    run_id = Column(Integer, ForeignKey("test_runs.run_id", ondelete="CASCADE"), nullable=False)
    
    # Test case details
    endpoint = Column(String, nullable=False)
    http_method = Column(Enum(HTTPMethod), nullable=False)
    test_type = Column(String, nullable=False)  # e.g., "missing_field", "wrong_type", "timeout"
    
    # Request/Response data
    request_payload = Column(JSON, nullable=True)
    response_snippet = Column(Text, nullable=True)  # Sanitized/trimmed
    status_code = Column(Integer, nullable=True)
    response_time_ms = Column(Float, nullable=True)
    
    # Failure details
    failure_reason = Column(String, nullable=False)  # Rule-based: "5xx_error", "timeout", etc.
    detected_at = Column(DateTime, default=datetime.utcnow)
    
    # Agent 2 analysis (only if failures exist)
    root_cause = Column(Text, nullable=True)
    risk_level = Column(Enum(FailureSeverity), nullable=True)
    fix_suggestion = Column(Text, nullable=True)
    
    # Relationships
    test_run = relationship("TestRun", back_populates="failures")
    
    __table_args__ = (
        Index('idx_run_endpoint', 'run_id', 'endpoint'),
    )